FROM ubuntu:16.04
RUN apt-get update && apt-get install -y --force-yes golang
COPY src /src
COPY web /web
COPY *.pem /

ENV GOPATH /
ENV DATA_SERVICE_URL http://172.18.0:4000
EXPOSE 3000
RUN go install github.com/secmohammed/web
ENTRYPOINT ["./bin/web"]
