FROM ubuntu:16.04
RUN apt-get update && apt-get install -y --force-yes golang
COPY src /src
COPY *.pem /
ENV GOPATH /
EXPOSE 4000
RUN go install github.com/secmohammed/dataservice
WORKDIR /
ENTRYPOINT ["./bin/dataservice"]
